package simconnect

// Exception Fail ID
const E_FAIL uint32 = 0x80004005

// DataType IDs
const (
	DATATYPE_INVALID      uint32 = iota // invalid data type
	DATATYPE_INT32                      // 32-bit integer number
	DATATYPE_INT64                      // 64-bit integer number
	DATATYPE_FLOAT32                    // 32-bit floating-point number (float)
	DATATYPE_FLOAT64                    // 64-bit floating-point number (double)
	DATATYPE_STRING8                    // 8-byte string
	DATATYPE_STRING32                   // 32-byte string
	DATATYPE_STRING64                   // 64-byte string
	DATATYPE_STRING128                  // 128-byte string
	DATATYPE_STRING256                  // 256-byte string
	DATATYPE_STRING260                  // 260-byte string
	DATATYPE_STRINGV                    // variable-length string
	DATATYPE_INITPOSITION               // see SIMCONNECT_DATA_INITPOSITION
	DATATYPE_MARKERSTATE                // see SIMCONNECT_DATA_MARKERSTATE
	DATATYPE_WAYPOINT                   // see SIMCONNECT_DATA_WAYPOINT
	DATATYPE_LATLONALT                  // see SIMCONNECT_DATA_LATLONALT
	DATATYPE_XYZ                        // see SIMCONNECT_DATA_XYZ
)

// Receive ID Types 接收消息类型
const (
	RECV_ID_NULL uint32 = iota
	RECV_ID_EXCEPTION
	RECV_ID_OPEN
	RECV_ID_QUIT
	RECV_ID_EVENT
	RECV_ID_EVENT_OBJECT_ADDREMOVE
	RECV_ID_EVENT_FILENAME
	RECV_ID_EVENT_FRAME
	RECV_ID_SIMOBJECT_DATA
	RECV_ID_SIMOBJECT_DATA_BYTYPE
	RECV_ID_WEATHER_OBSERVATION
	RECV_ID_CLOUD_STATE
	RECV_ID_ASSIGNED_OBJECT_ID
	RECV_ID_RESERVED_KEY
	RECV_ID_CUSTOM_ACTION
	RECV_ID_SYSTEM_STATE
	RECV_ID_CLIENT_DATA
	RECV_ID_EVENT_WEATHER_MODE
	RECV_ID_AIRPORT_LIST
	RECV_ID_VOR_LIST
	RECV_ID_NDB_LIST
	RECV_ID_WAYPOINT_LIST
	RECV_ID_EVENT_MULTIPLAYER_SERVER_STARTED
	RECV_ID_EVENT_MULTIPLAYER_CLIENT_STARTED
	RECV_ID_EVENT_MULTIPLAYER_SESSION_ENDED
	RECV_ID_EVENT_RACE_END
	RECV_ID_EVENT_RACE_LAP

	RECV_ID_PICK
)

// SimObject Types
const (
	SIMOBJECT_TYPE_USER uint32 = iota
	SIMOBJECT_TYPE_ALL
	SIMOBJECT_TYPE_AIRCRAFT
	SIMOBJECT_TYPE_HELICOPTER
	SIMOBJECT_TYPE_BOAT
	SIMOBJECT_TYPE_GROUND
)

const (
	SIMCONNECT_PERIOD_NEVER uint32 = iota
	SIMCONNECT_PERIOD_ONCE
	SIMCONNECT_PERIOD_VISUAL_FRAME
	SIMCONNECT_PERIOD_SIM_FRAME
	SIMCONNECT_PERIOD_SECOND
)

// Client Data Period 常量
const (
	SIMCONNECT_CLIENT_DATA_PERIOD_NEVER        = 0
	SIMCONNECT_CLIENT_DATA_PERIOD_ONCE         = 1
	SIMCONNECT_CLIENT_DATA_PERIOD_VISUAL_FRAME = 2
	SIMCONNECT_CLIENT_DATA_PERIOD_ON_SET       = 3
)

// Client Data Request Flag 常量
const (
	SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_DEFAULT = 0
	SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_CHANGED = 1
	SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_TAGGED  = 2
)

// Client Data Set Flag 常量
const (
	SIMCONNECT_CLIENT_DATA_SET_FLAG_DEFAULT = 0
	SIMCONNECT_CLIENT_DATA_SET_FLAG_TAGGED  = 1
)
