package simconnect

// HRESULT 是 Windows API 的返回值类型
type HRESULT uintptr

// SimConnect 常量
const (
	SIMCONNECT_UNUSED = 0xFFFFFFFF
)

// Period 常量 - 数据请求周期
const (
	SIMCONNECT_PERIOD_NEVER        = 0
	SIMCONNECT_PERIOD_ONCE         = 1
	SIMCONNECT_PERIOD_VISUAL_FRAME = 2
	SIMCONNECT_PERIOD_SIM_FRAME    = 3
	SIMCONNECT_PERIOD_SECOND       = 4
)

// Data Type 常量
const (
	SIMCONNECT_DATATYPE_INVALID   = 0
	SIMCONNECT_DATATYPE_INT32     = 1
	SIMCONNECT_DATATYPE_INT64     = 2
	SIMCONNECT_DATATYPE_FLOAT32   = 3
	SIMCONNECT_DATATYPE_FLOAT64   = 4
	SIMCONNECT_DATATYPE_STRING8   = 5
	SIMCONNECT_DATATYPE_STRING32  = 6
	SIMCONNECT_DATATYPE_STRING64  = 7
	SIMCONNECT_DATATYPE_STRING128 = 8
	SIMCONNECT_DATATYPE_STRING256 = 9
	SIMCONNECT_DATATYPE_STRING260 = 10
	SIMCONNECT_DATATYPE_STRINGV   = 11
)

// Client Data Period 常量
const (
	SIMCONNECT_CLIENT_DATA_PERIOD_NEVER        = 0
	SIMCONNECT_CLIENT_DATA_PERIOD_ONCE         = 1
	SIMCONNECT_CLIENT_DATA_PERIOD_VISUAL_FRAME = 2
	SIMCONNECT_CLIENT_DATA_PERIOD_ON_SET       = 3
)

// Client Data Request Flag 常量
const (
	SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_DEFAULT = 0
	SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_CHANGED = 1
	SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_TAGGED  = 2
)

// Client Data Set Flag 常量
const (
	SIMCONNECT_CLIENT_DATA_SET_FLAG_DEFAULT = 0
	SIMCONNECT_CLIENT_DATA_SET_FLAG_TAGGED  = 1
)

// Recv ID 常量 - 接收消息类型
const (
	SIMCONNECT_RECV_ID_NULL                   = 0
	SIMCONNECT_RECV_ID_EXCEPTION              = 1
	SIMCONNECT_RECV_ID_OPEN                   = 2
	SIMCONNECT_RECV_ID_QUIT                   = 3
	SIMCONNECT_RECV_ID_EVENT                  = 4
	SIMCONNECT_RECV_ID_EVENT_OBJECT_ADDREMOVE = 5
	SIMCONNECT_RECV_ID_EVENT_FILENAME         = 6
	SIMCONNECT_RECV_ID_EVENT_FRAME            = 7
	SIMCONNECT_RECV_ID_SIMOBJECT_DATA         = 8
	SIMCONNECT_RECV_ID_SIMOBJECT_DATA_BYTYPE  = 9
	SIMCONNECT_RECV_ID_CLOUD_STATE            = 10
	SIMCONNECT_RECV_ID_ASSIGNED_OBJECT_ID     = 11
	SIMCONNECT_RECV_ID_RESERVED_KEY           = 12
	SIMCONNECT_RECV_ID_CUSTOM_ACTION          = 13
	SIMCONNECT_RECV_ID_SYSTEM_STATE           = 14
	SIMCONNECT_RECV_ID_CLIENT_DATA            = 15
	SIMCONNECT_RECV_ID_EVENT_WEATHER_MODE     = 16
	SIMCONNECT_RECV_ID_AIRPORT_LIST           = 17
	SIMCONNECT_RECV_ID_VOR_LIST               = 18
	SIMCONNECT_RECV_ID_NDB_LIST               = 19
	SIMCONNECT_RECV_ID_WAYPOINT_LIST          = 20
)

// SimConnect 接收消息基础结构
type SIMCONNECT_RECV struct {
	DwSize    uint32
	DwVersion uint32
	DwID      uint32
}

// 客户端数据接收结构
type SIMCONNECT_RECV_CLIENT_DATA struct {
	SIMCONNECT_RECV
	RequestID   uint32
	ObjectID    uint32
	DefineID    uint32
	Flags       uint32
	EntryNumber uint32
	OutOf       uint32
	DefineCount uint32
}
